apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: platform-cluster

servers: 1
agents: 2

image: rancher/k3s:v1.29.6-k3s1

# https://127.0.0.1:6550
kubeAPI:
  host: "127.0.0.1"
  hostPort: "6550"

ports:
  # HTTP ingress
  - port: 8080:30080
    nodeFilters:
      - loadbalancer

  # HTTPS ingress
  - port: 8443:30443
    nodeFilters:
      - loadbalancer

  # Kafka external access
  - port: 9092:30992
    nodeFilters:
      - loadbalancer

  # Grafana
  - port: 3000:32044
    nodeFilters:
      - loadbalancer

  # Prometheus
  - port: 9090:32090
    nodeFilters:
      - loadbalancer

  # Rancher UI
  - port: 9443:30969
    nodeFilters:
      - loadbalancer

options:
  runtime:
    serversMemory: "4g"   
    agentsMemory: "4g"
    serversCPU: "2"
    agentsCPU: "2"

  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - server:*
      - arg: "--kube-apiserver-arg=--max-requests-inflight=100"
        nodeFilters:
          - server:*
      - arg: "--kube-apiserver-arg=--max-mutating-requests-inflight=50"
        nodeFilters:
          - server:*

volumes:
  - volume: "D:\\data:/data"
    nodeFilters:
      - all
  - volume: "./volumes:/var/lib/rancher/k3s/storage"
    nodeFilters:
      - all