apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: platform-cluster

servers: 1
agents: 2

# Docker image used by k3s
image: rancher/k3s:v1.29.6-k3s1

# Expose ports from cluster → localhost
ports:
  # -----------------------------------
  # Ingress Controller (HTTP)
  # Access all dashboards via browser
  # -----------------------------------
  - port: 8080:30080@loadbalancer

  # -----------------------------------
  # Ingress Controller (HTTPS)
  # -----------------------------------
  - port: 8443:30443@loadbalancer

  # -----------------------------------
  # Kafka External Listener
  # Required for local producers/consumers
  # -----------------------------------
  - port: 9092:30992@loadbalancer

  # -----------------------------------
  # Grafana direct access (optional)
  # -----------------------------------
  - port: 3000:32044@loadbalancer

  # -----------------------------------
  # Prometheus UI (optional debugging)
  # -----------------------------------
  - port: 9090:32090@loadbalancer

  # -----------------------------------
  # Rancher UI
  # -----------------------------------
  - port: 9443:30443@loadbalancer

options:
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - server:*

# Useful for local development networking
kubeAPI:
  host: "0.0.0.0"
  hostPort: "6550"

# Volumes for persistence (optional future use)
volumes:
  - volume: ./volumes:/var/lib/rancher/k3s/storage@all