apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: kafka-pool
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster

spec:
  replicas: 2

  roles:
    - broker
    - controller

  storage:
    type: persistent-claim
    size: 5Gi
    deleteClaim: false