storageClass:
  defaultClass: true
  name: local-path

configmap:
  name: local-path-config
  data:
    config.json: |-
      {
        "nodePathMap": [
          {
            "node": "DEFAULT_PATH_FOR_NON_LISTED_NODES",
            "paths": ["/data"]
          }
        ]
      }